### ISSUE TITLE
Not an issue. Setup question

### ISSUE THREAD

**Issue by securisec** [alexhude/uEmu#3]
Awesome plugin! Wish i knew how to use it. I placed the plugin in my ida pro plugin directory, but i dont see it appear either in the right click menu, or in the plugins menu. Using latest IDA7 for mac. Trying to run the script directly does throw a NameError `is_code` is not defined, but this could be due to me not setting it up properly. 

Any suggestions on how to set it up besides what i am already trying?

Thanks!

**Comment by alexhude** [comment]
I have pushed some fixes to make it work as a plugin in cbaa285cda836b33d2ef57d05bb1ca9738908cff. 
Just change `USE_AS_SCRIPT` to `False` inside **uEmu.py**

However, NameError seems to be caused by your IDA python setup.
For example `is_code` is referenced in uEmu like that:
```
from idaapi import *
from idc import *

if IDA_SDK_VERSION >= 700:
    IDAAPI_IsCode       = is_code
```
in `idaapi.py` we can see:
```
7: from ida_bytes import *
```
and finally in `ida_bytes.py`:
```
497: def is_code(*args):
498:     ...
```

So it is 100% available in IDA 7 python SDK.

**Comment by securisec** [comment]
Gotcha. Thanks! That was very helpful. I think i figured out what my core issue was. IDA 7 does not see my unicorn install in brew python, so it is fighting me. setting a sys path insert didnt fix, but i will keep poking at it. Thanks for making awesomeness!

**Comment by alexhude** [comment]
Correct. IDA uses default macOS python. Use this command to make unicorn available in IDA:
`sudo /System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7 -m pip install unicorn`
